version: '3.8'

networks:
  app_network:
    driver: bridge

volumes:
  mariadb_data:

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${APP_SLUG}_php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app_network
    depends_on:
      - mariadb

  nginx:
    image: nginx:alpine
    container_name: ${APP_SLUG}_nginx
    restart: unless-stopped
    ports:
      - "8811:80"
    extra_hosts:
      host.docker.internal: host-gateway
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    depends_on:
      - mariadb

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${APP_SLUG}_myadmin
    restart: unless-stopped
    ports:
      - 8812:80
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./phpmyadmin/php.ini:/usr/local/etc/php/conf.d/${APP_SLUG}-php.ini
    networks:
      - app_network

  mariadb:
    image: mariadb:latest
    container_name: ${APP_SLUG}_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8813:3306
    volumes:
      - mariadb_data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - app_network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${APP_SLUG}_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8814:8025"
    networks:
      - app_network
